# # command to create installer
# # 1. need to make installer for windows, macos, and linux
# # 2. need to figure out versioning...
# pyinstaller --name "RAVE" --windowed --hidden-import moderngl_window.context.pyglet --hidden-import glcontext --clean cli.py

# # add to releases within github repo


name: Build Installer & Release

on:
  push:
    branches:
      - main
  
jobs:
  build:
    strategy:
      os: [
        ubuntu-latest,
        macos-latest,
        windows-latest
      ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install Poetry
        if: steps.cache_poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          export PATH="$HOME/.poetry/bin:$PATH"

        - name: Install dependencies
        run: poetry install

        - name: Build
          run: poetry pyinstaller --name "RAVE" --windowed --hidden-import moderngl_window.context.pyglet --hidden-import glcontext --clean cli.py
        
        - name: Create release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
              Initial release
            draft: false
            prerelease: false